# 优先级：System.getProperties() > application.yaml


# 基础配置: 通过bash根据环境来动态指定
root:
  dir: /Users/tbz/Payment
  port: 9527

# 网络配置
server:
  port: ${root.port}

# 日志配置
logging:
  config: classpath:log4j2.xml